-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "django_migrations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_migrations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"app" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"applied" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "django_content_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_content_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"app_label" varchar(100) NOT NULL,
	"model" varchar(100) NOT NULL,
	CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE("model","app_label")
);
--> statement-breakpoint
CREATE TABLE "auth_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"content_type_id" integer NOT NULL,
	"codename" varchar(100) NOT NULL,
	CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE("content_type_id","codename")
);
--> statement-breakpoint
CREATE TABLE "auth_group" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(150) NOT NULL,
	CONSTRAINT "auth_group_name_key" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "auth_group_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_group_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"group_id" integer NOT NULL,
	"permission_id" integer NOT NULL,
	CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE("permission_id","group_id")
);
--> statement-breakpoint
CREATE TABLE "auth_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"password" varchar(128) NOT NULL,
	"last_login" timestamp with time zone,
	"is_superuser" boolean NOT NULL,
	"username" varchar(150) NOT NULL,
	"first_name" varchar(150) NOT NULL,
	"last_name" varchar(150) NOT NULL,
	"email" varchar(254) NOT NULL,
	"is_staff" boolean NOT NULL,
	"is_active" boolean NOT NULL,
	"date_joined" timestamp with time zone NOT NULL,
	CONSTRAINT "auth_user_username_key" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "auth_user_groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_user_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"group_id" integer NOT NULL,
	CONSTRAINT "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE("user_id","group_id")
);
--> statement-breakpoint
CREATE TABLE "auth_user_user_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_user_user_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"permission_id" integer NOT NULL,
	CONSTRAINT "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE("user_id","permission_id")
);
--> statement-breakpoint
CREATE TABLE "django_admin_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_admin_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"action_time" timestamp with time zone NOT NULL,
	"object_id" text,
	"object_repr" varchar(200) NOT NULL,
	"action_flag" smallint NOT NULL,
	"change_message" text NOT NULL,
	"content_type_id" integer,
	"user_id" integer NOT NULL,
	CONSTRAINT "django_admin_log_action_flag_check" CHECK (action_flag >= 0)
);
--> statement-breakpoint
CREATE TABLE "events_venue" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "events_venue_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"address" varchar(500) NOT NULL,
	"city" varchar(120) NOT NULL,
	"country" varchar(120) NOT NULL,
	"website" varchar(2000) NOT NULL,
	"latitude" double precision,
	"longitude" double precision,
	"source" varchar(120) NOT NULL,
	"source_url" varchar(2000) NOT NULL,
	"scraped_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"place_id" varchar(255) NOT NULL,
	"about" text NOT NULL,
	"amenities" jsonb NOT NULL,
	"price_level" varchar(40) NOT NULL,
	"primary_type" varchar(120) NOT NULL,
	"primary_type_display" varchar(120) NOT NULL,
	"rating" double precision,
	"types" jsonb NOT NULL,
	"verification_status" varchar(20) DEFAULT '' NOT NULL,
	"agents_primary_types" jsonb NOT NULL,
	CONSTRAINT "events_venue_slug_key" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "django_session" (
	"session_key" varchar(40) PRIMARY KEY NOT NULL,
	"session_data" text NOT NULL,
	"expire_date" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "events_event" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "events_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(300) NOT NULL,
	"slug" varchar(300) NOT NULL,
	"description" text NOT NULL,
	"starts_at" timestamp with time zone,
	"ends_at" timestamp with time zone,
	"url" varchar(2000) NOT NULL,
	"image_url" varchar(2000) NOT NULL,
	"price" varchar(120) NOT NULL,
	"category" varchar(120) NOT NULL,
	"source" varchar(120) NOT NULL,
	"source_url" varchar(2000) NOT NULL,
	"external_id" varchar(255) NOT NULL,
	"scraped_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"venue_id" bigint,
	"organizer" varchar(255) NOT NULL,
	"organizer_url" varchar(2000) NOT NULL,
	"organizer_ref_id" bigint,
	"agent_categories" jsonb NOT NULL,
	"search_query_id" bigint,
	"registration_url" varchar(2000) NOT NULL,
	CONSTRAINT "events_event_slug_key" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "events_searchquery" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "events_searchquery_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"query" varchar(500) NOT NULL,
	"source" varchar(120) NOT NULL,
	"is_active" boolean NOT NULL,
	"last_run_at" timestamp with time zone,
	"events_found_count" integer NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "unique_source_query" UNIQUE("source","query")
);
--> statement-breakpoint
CREATE TABLE "events_scraperrun" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "events_scraperrun_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"scraper_key" varchar(120) NOT NULL,
	"status" varchar(20) NOT NULL,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"created_count" integer NOT NULL,
	"updated_count" integer NOT NULL,
	"extra_counts" jsonb NOT NULL,
	"error_message" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"triggered_by_id" integer,
	"pid" integer,
	"log_output" text NOT NULL,
	CONSTRAINT "events_scraperrun_pid_check" CHECK (pid >= 0)
);
--> statement-breakpoint
CREATE TABLE "events_organizer" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "events_organizer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"status" varchar(20) NOT NULL,
	"website" varchar(200) NOT NULL,
	"email" varchar(254) NOT NULL,
	"phone" varchar(80) NOT NULL,
	"address" varchar(500) NOT NULL,
	"city" varchar(120) NOT NULL,
	"country" varchar(120) NOT NULL,
	"facebook_url" varchar(200) NOT NULL,
	"instagram_url" varchar(200) NOT NULL,
	"description" text NOT NULL,
	"source" varchar(120) NOT NULL,
	"source_url" varchar(200) NOT NULL,
	"external_id" varchar(255) NOT NULL,
	"scraped_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"enriched_at" timestamp with time zone,
	"enrichment_source" varchar(120) NOT NULL,
	CONSTRAINT "events_organizer_slug_key" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events_event" ADD CONSTRAINT "events_event_venue_id_ffde28fd_fk_events_venue_id" FOREIGN KEY ("venue_id") REFERENCES "public"."events_venue"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events_event" ADD CONSTRAINT "events_event_organizer_ref_id_6162f247_fk_events_organizer_id" FOREIGN KEY ("organizer_ref_id") REFERENCES "public"."events_organizer"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events_event" ADD CONSTRAINT "events_event_search_query_id_32555112_fk_events_searchquery_id" FOREIGN KEY ("search_query_id") REFERENCES "public"."events_searchquery"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events_scraperrun" ADD CONSTRAINT "events_scraperrun_triggered_by_id_0e0b19fc_fk_auth_user_id" FOREIGN KEY ("triggered_by_id") REFERENCES "public"."auth_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" USING btree ("content_type_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" USING btree ("name" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" USING btree ("group_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" USING btree ("permission_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_user_username_6821ab7c_like" ON "auth_user" USING btree ("username" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" USING btree ("group_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" USING btree ("user_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" USING btree ("permission_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" USING btree ("user_id" int4_ops);--> statement-breakpoint
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" USING btree ("content_type_id" int4_ops);--> statement-breakpoint
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" USING btree ("user_id" int4_ops);--> statement-breakpoint
CREATE INDEX "events_venue_place_id_9ea721b9" ON "events_venue" USING btree ("place_id" text_ops);--> statement-breakpoint
CREATE INDEX "events_venue_place_id_9ea721b9_like" ON "events_venue" USING btree ("place_id" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "events_venue_primary_type_display_ed5f46f6" ON "events_venue" USING btree ("primary_type_display" text_ops);--> statement-breakpoint
CREATE INDEX "events_venue_primary_type_display_ed5f46f6_like" ON "events_venue" USING btree ("primary_type_display" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "events_venue_slug_a9f7b8c8_like" ON "events_venue" USING btree ("slug" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "events_venue_verification_status_cd9fff7e" ON "events_venue" USING btree ("verification_status" text_ops);--> statement-breakpoint
CREATE INDEX "events_venue_verification_status_cd9fff7e_like" ON "events_venue" USING btree ("verification_status" varchar_pattern_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "unique_venue_source_place_id" ON "events_venue" USING btree ("source" text_ops,"place_id" text_ops) WHERE ((place_id)::text > ''::text);--> statement-breakpoint
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" USING btree ("expire_date" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" USING btree ("session_key" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "events_event_external_id_3614f13d" ON "events_event" USING btree ("external_id" text_ops);--> statement-breakpoint
CREATE INDEX "events_event_external_id_3614f13d_like" ON "events_event" USING btree ("external_id" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "events_event_organizer_ref_id_6162f247" ON "events_event" USING btree ("organizer_ref_id" int8_ops);--> statement-breakpoint
CREATE INDEX "events_event_search_query_id_32555112" ON "events_event" USING btree ("search_query_id" int8_ops);--> statement-breakpoint
CREATE INDEX "events_event_slug_b44b2c04_like" ON "events_event" USING btree ("slug" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "events_event_venue_id_ffde28fd" ON "events_event" USING btree ("venue_id" int8_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "unique_source_external_id" ON "events_event" USING btree ("source" text_ops,"external_id" text_ops) WHERE ((external_id)::text > ''::text);--> statement-breakpoint
CREATE INDEX "events_searchquery_is_active_4a99a794" ON "events_searchquery" USING btree ("is_active" bool_ops);--> statement-breakpoint
CREATE INDEX "events_scraperrun_scraper_key_671ad7a7" ON "events_scraperrun" USING btree ("scraper_key" text_ops);--> statement-breakpoint
CREATE INDEX "events_scraperrun_scraper_key_671ad7a7_like" ON "events_scraperrun" USING btree ("scraper_key" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "events_scraperrun_status_4d2f1125" ON "events_scraperrun" USING btree ("status" text_ops);--> statement-breakpoint
CREATE INDEX "events_scraperrun_status_4d2f1125_like" ON "events_scraperrun" USING btree ("status" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "events_scraperrun_triggered_by_id_0e0b19fc" ON "events_scraperrun" USING btree ("triggered_by_id" int4_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "unique_active_scraper_run" ON "events_scraperrun" USING btree ("scraper_key" text_ops) WHERE ((status)::text = ANY ((ARRAY['queued'::character varying, 'running'::character varying])::text[]));--> statement-breakpoint
CREATE INDEX "events_organizer_external_id_b6e38bba" ON "events_organizer" USING btree ("external_id" text_ops);--> statement-breakpoint
CREATE INDEX "events_organizer_external_id_b6e38bba_like" ON "events_organizer" USING btree ("external_id" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "events_organizer_slug_d270e2a4_like" ON "events_organizer" USING btree ("slug" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "events_organizer_status_7939e7fb" ON "events_organizer" USING btree ("status" text_ops);--> statement-breakpoint
CREATE INDEX "events_organizer_status_7939e7fb_like" ON "events_organizer" USING btree ("status" varchar_pattern_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "unique_organizer_source_external_id" ON "events_organizer" USING btree ("source" text_ops,"external_id" text_ops) WHERE ((external_id)::text > ''::text);
*/